name: pages
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy-pages:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install -g yarn

            - name: install
              working-directory: ./
              run: yarn

            - name: build
              working-directory: ./
              run: yarn build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: dist/
